### ISSUE TITLE
overlap: Estimates of Coefficient of Overlapping for Animal Activity Patterns

### ISSUE THREAD

**Issue by mdsumner** [rociojoo/CranTaskView-Track#7]
**Is it on CRAN?**  
Yes

https://CRAN.R-project.org/package=overlap 

https://github.com/mikemeredith/overlap

**Are you the author of this package?**  
No. 

(will try to follow up on more later - mdsumner)

**If you are the author, does it pass check CRAN tests?**  
Yes/No/I don't know. 

**Additional information:**  
In order to be included in the CTV Tracking, we would appreciate more information to help us determine how the package fits into the Tracking CTV scope.  

Briefly, can you describe the purpose of this package and how it fits into the Tracking CTV?  

In terms of the tracking workflow (see Figure in the CTV), where does the package fit? (Feel free to mention any particular functions and how they fit as well.)

**Comment by birderboone** [comment]
Thank you for the submission. We're updating the task view now and will update you on the status!

**Comment by birderboone** [comment]
We've deliberated a lot, and currently because the package does not relate to individual identities but instead exists at a species level it would not fit under the Tracking definition. Additionally while there is an implicit x,y,t for each camera, the x and y dont seem to be involved in the calculations either.

I am curious on your thoughts.

**Comment by mdsumner** [comment]
Oh I don't mind, I don't see any negative to including something, is all. I wouldn't spend more time on it.

**Comment by birderboone** [comment]
Thanks, Michael. I'll close it for now.
